version: "3"

services:
  fastapi-app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    image: theydo
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./app
        target: /app
