version: "3"

services:
  fastapi-app:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-app
    image: sentiment-analysis-api
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./api
        target: /app
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.streamlit
    container_name: st-app
    image: streamlit-frontend
    environment:
      IP_ADDRESS: "fastapi-app:8000"
    ports:
      - 8501:8501
    # volumes:
    #   - type: bind
    #     source: ./frontend
    #     target: /app
