version: "3"

services:
  fastapi-app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    image: theydo
    ports:
      - 8000:8000
